install.packages("data.table",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("Metrics",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("Rtsne",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("ggplot2",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("ClusterR",repos= "http://lib.stat.cmu.edu/R/CRAN/")
